name: 'Create future branch'
description: 'Create future/** branch'
inputs:

  prefix:
    description: The prefix of the future branch.
    required: true
    default: ws

  init:
    description: Script for initialization of the future branch.
    required: true

  labels:
    type: string
    required: false
    default: ''
    description: A comma or newline-separated list of labels.

  base:
    type: string
    required: false
    default: ''
    description: The name of the base branch of the pull request.

outputs:

  branch:
    description: The full name of the future branch.
    value: ${{ steps.meta.outputs.branch }}

  branch-name:
    description: The name of the future branch (without the `future/` part).
    value: ${{ steps.meta.outputs.branch-name }}

  pull-request-number:
    description: The pull request number.
    value: ${{ steps.create-pull-request.outputs.pull-request-number }}

  pull-request-url:
    description: The URL of the pull request.
    value: ${{ steps.create-pull-request.outputs.pull-request-url }}

runs:

  using: "composite"
  steps:

    - run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: meta.py --prefix "${{ inputs.prefix }}" >> "$GITHUB_OUTPUT"
      id: meta
      shell: bash

    - name: Initialize future branch
      if: ${{ inputs.init != '' }}
      run: ${{ inputs.init }} "${{ steps.meta.outputs.branch }}"
      shell: bash
  
    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      id: create-pull-request
      with:
        title: Merge future branch ${{ steps.meta.outputs.branch-name }}
        labels: ${{ inputs.labels }}
        body: ''
        branch: ${{ steps.meta.outputs.branch }}
        commit-message: Initialize future branch
        base: ${{ inputs.base }}
