name: Create example future branch

on:
  push:
    paths:
      - '.github/workflows/example.yml'
      - 'action.yml'
      - 'create-future-branch.py'
  pull_request:
    branches:
      - 'master'
      - 'future/**'

jobs:

  test_example:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - uses: kostrykin/create-future-branch-action@master
        with:
          init: python example/init-future-branch.py